*&---------------------------------------------------------------------*
*& Include          ZACG_MAINS01
*&---------------------------------------------------------------------*


**********************************************************************
***             SELECTION SCREEN FOR ROLE ANALYSIS
**********************************************************************
SELECTION-SCREEN BEGIN OF SCREEN 0001 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-b00.

    PARAMETERS p_role TYPE zacg_role_type AS LISTBOX
    VISIBLE LENGTH 10 USER-COMMAND rty MODIF ID md1.
    SELECT-OPTIONS s_srole FOR g_srole MODIF ID md2.
    SELECT-OPTIONS s_crole FOR g_crole MODIF ID md3.
    SELECT-OPTIONS s_rmod FOR g_module NO INTERVALS MODIF ID md4.

    SELECTION-SCREEN BEGIN OF BLOCK b11 WITH FRAME TITLE TEXT-b02.
      SELECTION-SCREEN BEGIN OF LINE.
        PARAMETERS p_rlvl0    AS CHECKBOX USER-COMMAND rv10 MODIF ID md4.
        SELECTION-SCREEN COMMENT 3(10) TEXT-c01 MODIF ID md4.
        PARAMETERS p_rlvl1    AS CHECKBOX USER-COMMAND rv11 MODIF ID md4.
        SELECTION-SCREEN COMMENT 16(10) TEXT-c02 MODIF ID md4.
        PARAMETERS p_rlvl2    AS CHECKBOX USER-COMMAND rv12 MODIF ID md4.
        SELECTION-SCREEN COMMENT 29(10) TEXT-c03 MODIF ID md4.
        PARAMETERS p_rlvl3    AS CHECKBOX USER-COMMAND rv13 MODIF ID md4.
        SELECTION-SCREEN COMMENT 42(10) TEXT-c04.
        PARAMETERS p_rlvl4    AS CHECKBOX USER-COMMAND rv14 MODIF ID md4.
        SELECTION-SCREEN COMMENT 55(10) TEXT-c05 MODIF ID md4.
      SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN END OF BLOCK b11.

    SELECTION-SCREEN BEGIN OF BLOCK b12 WITH FRAME TITLE TEXT-b03.
      PARAMETERS r_sum RADIOBUTTON GROUP rg1 DEFAULT 'X' MODIF ID md4.
      PARAMETERS r_dtl RADIOBUTTON GROUP rg1 MODIF ID md4.
    SELECTION-SCREEN END OF BLOCK b12.


    SELECTION-SCREEN BEGIN OF BLOCK b13 WITH FRAME TITLE TEXT-b01.
      SELECTION-SCREEN BEGIN OF LINE.
        PARAMETERS p_rsimu  AS CHECKBOX MODIF ID md3.
        SELECTION-SCREEN COMMENT 3(29) TEXT-c06 MODIF ID md3.
        SELECTION-SCREEN PUSHBUTTON 32(20) rsimfrmt USER-COMMAND dfmt MODIF ID md3
          VISIBLE LENGTH 20.
      SELECTION-SCREEN END OF LINE.
      PARAMETERS p_rfile TYPE localfile MODIF ID md3.
    SELECTION-SCREEN END OF BLOCK b13.

    SELECTION-SCREEN BEGIN OF BLOCK b14 WITH FRAME TITLE TEXT-b05.
      SELECTION-SCREEN PUSHBUTTON 2(20) rexecute USER-COMMAND &rex MODIF ID md4
        VISIBLE LENGTH 20.
    SELECTION-SCREEN END OF BLOCK b14.

  SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN END OF SCREEN 0001.

**********************************************************************
***             SELECTION SCREEN FOR USER ANALYSIS
**********************************************************************
SELECTION-SCREEN BEGIN OF SCREEN 0002 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-b00.
    SELECT-OPTIONS s_user FOR g_user.
    SELECT-OPTIONS s_umod FOR g_module NO INTERVALS.

    SELECTION-SCREEN BEGIN OF BLOCK b21 WITH FRAME TITLE TEXT-b02.
      SELECTION-SCREEN BEGIN OF LINE.
        PARAMETERS p_ulvl0    AS CHECKBOX USER-COMMAND uv10.
        SELECTION-SCREEN COMMENT 3(10) TEXT-c01.
        PARAMETERS p_ulvl1    AS CHECKBOX USER-COMMAND uv11.
        SELECTION-SCREEN COMMENT 16(10) TEXT-c02.
        PARAMETERS p_ulvl2    AS CHECKBOX USER-COMMAND rv12.
        SELECTION-SCREEN COMMENT 29(10) TEXT-c03.
        PARAMETERS p_ulvl3    AS CHECKBOX USER-COMMAND uv13.
        SELECTION-SCREEN COMMENT 42(10) TEXT-c04.
        PARAMETERS p_ulvl4    AS CHECKBOX USER-COMMAND uv14.
        SELECTION-SCREEN COMMENT 55(10) TEXT-c05.
      SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN END OF BLOCK b21.

    SELECTION-SCREEN BEGIN OF BLOCK b22 WITH FRAME TITLE TEXT-b03.
      PARAMETERS r_usum RADIOBUTTON GROUP rg2 DEFAULT 'X'.
      PARAMETERS r_udtl RADIOBUTTON GROUP rg2.
    SELECTION-SCREEN END OF BLOCK b22.

    SELECTION-SCREEN BEGIN OF BLOCK b23 WITH FRAME TITLE TEXT-b01.
      SELECTION-SCREEN BEGIN OF LINE.
        PARAMETERS p_usimu  AS CHECKBOX.
        SELECTION-SCREEN COMMENT 3(20) TEXT-c07.
        SELECTION-SCREEN PUSHBUTTON 31(20) usimfrmt USER-COMMAND ufmt
          VISIBLE LENGTH 20.
      SELECTION-SCREEN END OF LINE.
      PARAMETERS p_ufile TYPE localfile.
    SELECTION-SCREEN END OF BLOCK b23.

    SELECTION-SCREEN BEGIN OF BLOCK b24 WITH FRAME TITLE TEXT-b05.
      SELECTION-SCREEN PUSHBUTTON 2(20) uexecute USER-COMMAND &uex
        VISIBLE LENGTH 20.
    SELECTION-SCREEN END OF BLOCK b24.


  SELECTION-SCREEN END OF BLOCK b2.
SELECTION-SCREEN END OF SCREEN 0002.


**********************************************************************
***          SELECTION SCREEN FOR USER ROLE FILE UPLOAD
**********************************************************************
SELECTION-SCREEN BEGIN OF SCREEN 0006 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b6 WITH FRAME TITLE TEXT-bl1.
    PARAMETERS: p_file TYPE rlgrap-filename,
                p_srow TYPE i DEFAULT 3,
                p_erow TYPE i DEFAULT 99.
  SELECTION-SCREEN END OF BLOCK b6.
SELECTION-SCREEN END OF SCREEN 0006.

***Selection screen for Password Set /Reset
SELECTION-SCREEN BEGIN OF SCREEN 0007 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b71 WITH FRAME TITLE TEXT-bl2.
    SELECT-OPTIONS: so_upw FOR g_upw MODIF ID m02 NO INTERVALS.
    PARAMETERS: p_pwd    TYPE xuncode MODIF ID m02.
  SELECTION-SCREEN END OF BLOCK b71.

  SELECTION-SCREEN BEGIN OF BLOCK b72 WITH FRAME TITLE TEXT-bl4.
    PARAMETERS: p_file2 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK b72.
SELECTION-SCREEN END OF SCREEN 0007.


***Selection screen for Lock User
SELECTION-SCREEN BEGIN OF SCREEN 0008 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b81 WITH FRAME TITLE TEXT-bl5.
    PARAMETERS: p_dats   TYPE i.
  SELECTION-SCREEN END OF BLOCK b81.
SELECTION-SCREEN END OF SCREEN 0008.


*** Selection Screen For Set Productive Password
SELECTION-SCREEN BEGIN OF SCREEN 0009 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b83 WITH FRAME TITLE TEXT-b83.
    PARAMETERS: p_initpw TYPE rlgrap-filename.
  SELECTION-SCREEN END OF BLOCK b83.
SELECTION-SCREEN END OF SCREEN 0009.


*** Selection Screen For Update User Details
SELECTION-SCREEN BEGIN OF SCREEN 0010 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b84 WITH FRAME TITLE TEXT-b84.
    PARAMETERS: p_file3 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK b84.
SELECTION-SCREEN END OF SCREEN 0010.

*** Selection Screen to Role Change Description
SELECTION-SCREEN BEGIN OF SCREEN 0011 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b85 WITH FRAME TITLE TEXT-b85.
    PARAMETERS: p_file4 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK b85.
SELECTION-SCREEN END OF SCREEN 0011.

*** Selection Screen to Derive Role Creation
SELECTION-SCREEN BEGIN OF SCREEN 0012 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b86 WITH FRAME TITLE TEXT-b86.
    PARAMETERS: p_file5 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK b86.
SELECTION-SCREEN END OF SCREEN 0012.

*** Selection Screen to Delete Inheritence
SELECTION-SCREEN BEGIN OF SCREEN 0013 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b87 WITH FRAME TITLE TEXT-b87.
    PARAMETERS: p_file6 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK b87.
SELECTION-SCREEN END OF SCREEN 0013.

*** Selection Screen to Add Single Role to Composite
SELECTION-SCREEN BEGIN OF SCREEN 0014 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b88 WITH FRAME TITLE TEXT-b88.
    PARAMETERS: p_file7 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK b88.
SELECTION-SCREEN END OF SCREEN 0014.

*** Selection Screen to Remove Single from Composite
SELECTION-SCREEN BEGIN OF SCREEN 0015 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b89 WITH FRAME TITLE TEXT-b89.
    PARAMETERS: p_file8 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK b89.
SELECTION-SCREEN END OF SCREEN 0015.

*** Selection Screen to Delete Roles
SELECTION-SCREEN BEGIN OF SCREEN 0016 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b90 WITH FRAME TITLE TEXT-b90.
    PARAMETERS: p_file9 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK b90.
SELECTION-SCREEN END OF SCREEN 0016.

*** Selection Screen for Master Role Pushing
SELECTION-SCREEN BEGIN OF SCREEN 0017 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b91 WITH FRAME TITLE TEXT-b91.
    PARAMETERS: p_file10 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK b91.
SELECTION-SCREEN END OF SCREEN 0017.

*** Selection Screen to Create Composite Role( Blank )
SELECTION-SCREEN BEGIN OF SCREEN 0018 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b92 WITH FRAME TITLE TEXT-b92.
    PARAMETERS: p_file11 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK b92.
SELECTION-SCREEN END OF SCREEN 0018.

*** Selection Screen to Create Single Role( By Copying)
SELECTION-SCREEN BEGIN OF SCREEN 0019 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b93 WITH FRAME TITLE TEXT-b93.
    PARAMETERS: p_file12 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK b93.
SELECTION-SCREEN END OF SCREEN 0019.


*** Selection Screen for Role Assignment/Removal
SELECTION-SCREEN BEGIN OF SCREEN 0020 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b94 WITH FRAME TITLE TEXT-b94.
    SELECT-OPTIONS: so_crole FOR g_upw NO INTERVALS,
                    so_arole FOR g_role NO INTERVALS.
    PARAMETERS: rb_adr   RADIOBUTTON GROUP adr USER-COMMAND adr DEFAULT 'X',
                rb_der   RADIOBUTTON GROUP adr,
                p_fvalid TYPE sy-datum MODIF ID m04,
                p_tvalid TYPE sy-datum MODIF ID m04.
  SELECTION-SCREEN END OF BLOCK b94.
  SELECTION-SCREEN BEGIN OF BLOCK b95 WITH FRAME TITLE TEXT-b95.
    PARAMETERS: p_file13 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK b95.
SELECTION-SCREEN END OF SCREEN 0020.


*** Selection Screen for User Modification by Self
SELECTION-SCREEN BEGIN OF SCREEN 0022 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b96 WITH FRAME TITLE TEXT-b96.
    PARAMETERS: p_fdate TYPE cdhdr-udate DEFAULT sy-datum,
                p_ftime TYPE cdhdr-utime,
                p_tdate TYPE cdhdr-udate DEFAULT sy-datum,
                p_ttime TYPE cdhdr-utime DEFAULT '235959'.
  SELECTION-SCREEN END OF BLOCK b96.
SELECTION-SCREEN END OF SCREEN 0022.

*** Selection Screen for Mass Maintenance of Authorization Values
SELECTION-SCREEN BEGIN OF SCREEN 0023 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b97 WITH FRAME TITLE TEXT-b97.
    PARAMETERS: p_file14 TYPE rlgrap-filename .
    PARAMETERS : pa_add TYPE char1 RADIOBUTTON GROUP g1 DEFAULT 'X',
                 pa_adi TYPE char1 RADIOBUTTON GROUP g1, " With Instance
                 pa_ins TYPE char1 RADIOBUTTON GROUP g1,
                 pa_del TYPE char1 RADIOBUTTON GROUP g1,
                 pa_dli TYPE char1 RADIOBUTTON GROUP g1,
                 pa_din TYPE char1 RADIOBUTTON GROUP g1,
                 pa_ain TYPE char1 RADIOBUTTON GROUP g1,
                 pa_ani TYPE char1 RADIOBUTTON GROUP g1,
                 pa_atc TYPE char1 RADIOBUTTON GROUP g1,
                 pa_dtc TYPE char1 RADIOBUTTON GROUP g1,
                 pa_csr TYPE char1 RADIOBUTTON GROUP g1.
  SELECTION-SCREEN END OF BLOCK b97.
SELECTION-SCREEN END OF SCREEN 0023.

**** Selection Screen for Direct Changes in Derive Role
SELECTION-SCREEN BEGIN OF SCREEN 0024 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b98 WITH FRAME TITLE TEXT-b98.
    SELECT-OPTIONS : so_agr FOR g_agr_name.
  SELECTION-SCREEN END OF BLOCK b98.
SELECTION-SCREEN END OF SCREEN 0024.

**** Selection Screen for Direct change in Org Level Fields
SELECTION-SCREEN BEGIN OF SCREEN 0025 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b99 WITH FRAME TITLE TEXT-b99.
    SELECT-OPTIONS : so_agr1 FOR g_agr_name.
  SELECTION-SCREEN END OF BLOCK b99.
SELECTION-SCREEN END OF SCREEN 0025.


**** Selection Screen for Change User from Reference
SELECTION-SCREEN BEGIN OF SCREEN 0026 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK 9271 WITH FRAME TITLE TEXT-261.
    PARAMETERS: p_cufr TYPE suid_st_bname-bname.
    SELECT-OPTIONS : so_cufr FOR g_user NO INTERVALS.
  SELECTION-SCREEN END OF BLOCK 9271.
  SELECTION-SCREEN BEGIN OF BLOCK 9272 WITH FRAME TITLE TEXT-262.
    PARAMETERS: p_fcufr TYPE localfile.
  SELECTION-SCREEN END OF BLOCK 9272.
SELECTION-SCREEN END OF SCREEN 0026.

**** Selection Screen for New Access Request
SELECTION-SCREEN BEGIN OF SCREEN 0029 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK a929 WITH FRAME TITLE TEXT-263.
    PARAMETERS: p_nuser TYPE suid_st_bname-bname.
    SELECT-OPTIONS: s_nrole FOR g_agr_name NO INTERVALS.
  SELECTION-SCREEN END OF BLOCK a929.
SELECTION-SCREEN END OF SCREEN 0029.

**** Selection Screen for Bulk Access Request
SELECTION-SCREEN BEGIN OF SCREEN 0030 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK a930 WITH FRAME TITLE TEXT-264.
    PARAMETERS: p_file30 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK a930.
SELECTION-SCREEN END OF SCREEN 0030.


**** Selection Screen for Searcg Request
SELECTION-SCREEN BEGIN OF SCREEN 0031 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK a931 WITH FRAME TITLE TEXT-265.
    PARAMETERS: r_preq RADIOBUTTON GROUP 931 DEFAULT 'X' USER-COMMAND sreq.
    PARAMETERS: r_rreq RADIOBUTTON GROUP 931.
    PARAMETERS: r_creq RADIOBUTTON GROUP 931.
    PARAMETERS: r_sreq RADIOBUTTON GROUP 931.
    SELECT-OPTIONS: s_sreq FOR g_rreq NO INTERVALS MATCHCODE OBJECT zacg_role_req.
    SELECT-OPTIONS: s_susr FOR g_user NO INTERVALS.
  SELECTION-SCREEN END OF BLOCK a931.
SELECTION-SCREEN END OF SCREEN 0031.

**** Selection Screen for Searcg Request
SELECTION-SCREEN BEGIN OF SCREEN 0034 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK a934 WITH FRAME TITLE TEXT-266.
    SELECT-OPTIONS: s_usr34 FOR g_user NO INTERVALS.
  SELECTION-SCREEN END OF BLOCK a934.
SELECTION-SCREEN END OF SCREEN 0034.

****
SELECTION-SCREEN BEGIN OF SCREEN 0035 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK a935 WITH FRAME TITLE TEXT-266.
    SELECT-OPTIONS: s_dat35 FOR sy-datum.
    SELECT-OPTIONS: s_usr35 FOR g_user NO INTERVALS.
    SELECT-OPTIONS: s_fid35 FOR g_fusr NO INTERVALS MATCHCODE OBJECT zacg_ffid.
  SELECTION-SCREEN END OF BLOCK a935.
SELECTION-SCREEN END OF SCREEN 0035.

****
SELECTION-SCREEN BEGIN OF SCREEN 0036 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK a936 WITH FRAME TITLE TEXT-267.
    SELECTION-SCREEN BEGIN OF LINE.
      PARAMETERS rb_1y_36 RADIOBUTTON GROUP r36 USER-COMMAND rusg.
      SELECTION-SCREEN COMMENT 3(10) TEXT-c08.
      PARAMETERS rb_1m_36 RADIOBUTTON GROUP r36.
      SELECTION-SCREEN COMMENT 16(10) TEXT-c09.
      PARAMETERS rb_1w_36 RADIOBUTTON GROUP r36.
      SELECTION-SCREEN COMMENT 29(10) TEXT-c10.
    SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN BEGIN OF LINE.
      PARAMETERS rb_cd_36 RADIOBUTTON GROUP r36 DEFAULT 'X'.
      SELECTION-SCREEN COMMENT 3(7) TEXT-c11.
      SELECT-OPTIONS: s_dat36 FOR sy-datum.
    SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(9) TEXT-c12.
      SELECT-OPTIONS: s_usr36 FOR g_user NO INTERVALS.
    SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(9) TEXT-c13.
      SELECT-OPTIONS: s_tcd36 FOR g_tcode NO INTERVALS.
    SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK a936.
SELECTION-SCREEN END OF SCREEN 0036.

****
SELECTION-SCREEN BEGIN OF SCREEN 0037 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK a937 WITH FRAME TITLE TEXT-266.
    SELECT-OPTIONS: s_req37 FOR g_rreq NO INTERVALS MATCHCODE OBJECT zacg_role_req.
    SELECT-OPTIONS: s_usr37 FOR g_user NO INTERVALS.
    SELECT-OPTIONS: s_rol37 FOR g_agr_name NO INTERVALS.
  SELECTION-SCREEN END OF BLOCK a937.
SELECTION-SCREEN END OF SCREEN 0037.


SELECTION-SCREEN BEGIN OF SCREEN 0041 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK a941 WITH FRAME TITLE TEXT-268.
    PARAMETERS: rb_xls41 RADIOBUTTON GROUP r41 DEFAULT 'X' USER-COMMAND com41.
    PARAMETERS: rb_txt41 RADIOBUTTON GROUP r41.
    PARAMETERS: p_fil411 TYPE rlgrap-filename.
    PARAMETERS: p_fil412 TYPE rlgrap-filename .
  SELECTION-SCREEN END OF BLOCK a941.
SELECTION-SCREEN END OF SCREEN 0041.

SELECTION-SCREEN BEGIN OF SCREEN 0042 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK a942 WITH FRAME TITLE TEXT-269.
    PARAMETERS: rb_xls42 RADIOBUTTON GROUP r42 DEFAULT 'X' USER-COMMAND com42.
    PARAMETERS: rb_txt42 RADIOBUTTON GROUP r42.
    PARAMETERS: p_file42 TYPE rlgrap-filename.
  SELECTION-SCREEN END OF BLOCK a942.
SELECTION-SCREEN END OF SCREEN 0042.


**** Value Help -------------------------------------------
*** Value Help for Update User Details
AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file3.
  PERFORM get_filepath CHANGING p_file3.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file4.
  PERFORM get_filepath CHANGING p_file4.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file5.
  PERFORM get_filepath CHANGING p_file5.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file6.
  PERFORM get_filepath CHANGING p_file6.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file7.
  PERFORM get_filepath CHANGING p_file7.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file8.
  PERFORM get_filepath CHANGING p_file8.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file9.
  PERFORM get_filepath CHANGING p_file9.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file10.
  PERFORM get_filepath CHANGING p_file10.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file11.
  PERFORM get_filepath CHANGING p_file11.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file12.
  PERFORM get_filepath CHANGING p_file12.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_initpw.
  PERFORM get_filepath CHANGING p_initpw.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file13.
  PERFORM get_filepath CHANGING p_file13.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file14.
  PERFORM get_filepath CHANGING p_file14.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_fcufr.
  PERFORM get_filepath CHANGING p_fcufr.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file30.
  PERFORM get_filepath CHANGING p_file30.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_fil411.
  PERFORM get_filepath_xlsx_txt_41 CHANGING p_fil411.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_fil412.
  PERFORM get_filepath_xlsx_txt_41 CHANGING p_fil412.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_file42.
  PERFORM get_filepath_xlsx_txt_42 CHANGING p_file42.
