*&---------------------------------------------------------------------*
*& Include          ZACG_MAINTOP
*&---------------------------------------------------------------------*
TYPES: BEGIN OF ty_usr_output,
         userid   TYPE bapibname-bapibname,
         gen_pw   TYPE xuncode,
         user_msg TYPE bapi_msg,
         role_msg TYPE bapi_msg,
         prof_msg TYPE bapi_msg,
       END OF ty_usr_output,

       BEGIN OF ty_pwd_output,
         userid   TYPE bapibname-bapibname,
         pwd      TYPE xuncode,
         msg_ty   TYPE bapi_mtype,
         pwd_msg  TYPE bapi_msg,
         mail_msg TYPE bapi_msg,
       END OF ty_pwd_output,

       BEGIN OF ty_lock_output,
         userid    TYPE bapibname-bapibname,
         locked    TYPE xuuflag_alv,
         lock_msg  TYPE bapi_msg,
         mail_sent TYPE xuuflag_alv,
         mail_msg  TYPE bapi_msg,
       END OF ty_lock_output,

       BEGIN OF ty_role_des,
         role    TYPE agr_name,
         desc    TYPE agr_title,
         type    TYPE bapi_mtype,
         message TYPE bapi_msg,
       END OF ty_role_des,

       BEGIN OF ty_dr_role,
         prole   TYPE par_agr,
         crole   TYPE agr_name,
         type    TYPE bapi_mtype,
         message TYPE bapi_msg,
       END OF ty_dr_role,

       BEGIN OF ty_comp_role,
         comp_role TYPE agr_name,
         srole     TYPE agr_name,
         srole_txt TYPE agr_title,
         type      TYPE bapi_mtype,
         message   TYPE bapi_msg,
       END OF ty_comp_role,

       BEGIN OF ty_del_role,
         role    TYPE agr_name,
         type    TYPE bapi_mtype,
         message TYPE bapi_msg,
       END OF ty_del_role,

       BEGIN OF ty_ccomp_role,
         role    TYPE agr_name,
         desc    TYPE agr_title,
         type    TYPE bapi_mtype,
         message TYPE bapi_msg,
       END OF ty_ccomp_role,

       BEGIN OF ty_copy_role,
         org_role TYPE agr_name,
         new_role TYPE agr_name,
         type     TYPE bapi_mtype,
         message  TYPE bapi_msg,
       END OF ty_copy_role,

       BEGIN OF ty_role_output,
         userid   TYPE bapibname-bapibname,
         role_msg TYPE bapi_msg,
       END OF ty_role_output,

       BEGIN OF ty_user_details,
         userid     TYPE xubname,
         firstname  TYPE ad_namefir,
         lastname   TYPE ad_namelas,
         department TYPE ad_dprtmnt,
         function   TYPE ad_fnctn,
         e_mail     TYPE ad_smtpadr,
         type       TYPE bapi_mtype,
         message    TYPE bapi_msg,
       END OF ty_user_details,

       BEGIN OF ty_auth_val,
         role    TYPE agr_name,
         object  TYPE xuobject,
         field   TYPE agrfield,
         value   TYPE agval,
         type    TYPE char10,
         message TYPE bapi_msg,
       END OF ty_auth_val,

       BEGIN OF ty_outtab_9009,
         type TYPE icon_d,
         user TYPE xubname,
         msg  TYPE bapi_msg,
       END OF ty_outtab_9009,

       BEGIN OF ty_derive_role,
         role   TYPE agr_name,
         parent TYPE agr_name,
         object	TYPE agobject,
         auth	  TYPE agauth,
         field  TYPE agrfield,
         low    TYPE agval,
         high	  TYPE agval,
         status TYPE char50,
       END OF ty_derive_role,

       BEGIN OF ty_org_field,
         role   TYPE agr_name,
         object	TYPE agobject,
         field  TYPE agrfield,
         low    TYPE agval,
         high	  TYPE agval,
       END OF ty_org_field,

       BEGIN OF ty_users,
         bname   TYPE xubname,
         profile TYPE	xuprofile,
       END OF ty_users,

       ty_node_table_type TYPE STANDARD TABLE OF sapwltreen,

       BEGIN OF ty_logo_table,
         line(255) TYPE x,
       END OF ty_logo_table,

       BEGIN OF ty_outtab_9027,
         icon  TYPE icon_d,
         fuser TYPE xubname,
         tuser TYPE xubname,
         mesg  TYPE text100,
         box   TYPE c,
       END OF ty_outtab_9027,

       BEGIN OF ty_outtab_9028,
         user      TYPE xubname,
         role      TYPE agr_name,
         profile   TYPE xuprofile,
         adate     TYPE datum,
         atime     TYPE uzeit,
         ddate     TYPE datum,
         dtime     TYPE uzeit,
         duration  TYPE char100,
         atcode    TYPE tcode,
         dtcode    TYPE tcode,
         aernam    TYPE ernam,
         dernam    TYPE ernam,
         agr_fdate TYPE suid_change_from_dat,
         box       TYPE c,
       END OF ty_outtab_9028,

       BEGIN OF ty_outtab_9029,
         icon     TYPE icon_d,
         req_no   TYPE zacg_acc_req,
         user     TYPE xubname,
         role     TYPE agr_name,
         begda    TYPE begda,
         endda    TYPE endda,
         approver TYPE xubname,
         app_role TYPE xubname,
         status   TYPE zacg_acc_req_st,
         statust  TYPE string,
         ernam    TYPE ernam,
         erdat    TYPE erdat,
         box      TYPE c,
       END OF ty_outtab_9029,

       BEGIN OF ty_outtab_9031,
         icon         TYPE icon_d,
         req_no       TYPE zacg_acc_req,
         user         TYPE xubname,
         role         TYPE agr_name,
         begda        TYPE begda,
         endda        TYPE endda,
         approver     TYPE xubname,
         app_role     TYPE xubname,
         status       TYPE zacg_acc_req_st,
         statust      TYPE string,
         action_taken TYPE xfeld,
         ernam        TYPE ernam,
         erdat        TYPE erdat,
         box          TYPE c,
         org_req_no   TYPE zacg_acc_req,   " ++ Rounak
       END OF ty_outtab_9031,

       BEGIN OF ty_outtab_8007,
         req_no   TYPE zacg_acc_req,
         approver TYPE xubname,
         reqtype  TYPE string,
         begda    TYPE begda,
         endda    TYPE endda,
         mowner   TYPE xubname,
         user     TYPE xubname,
*         composite TYPE agr_name,
         agr_name TYPE agr_name,
         risk     TYPE zrisk,
         riskd    TYPE zrisk_descr,
         level    TYPE zrisk_level,
         leveld   TYPE val_text,
         type     TYPE xfeld,
         typed    TYPE val_text,
         module   TYPE zrisk_proc,
         moduled  TYPE val_text,
         sel      TYPE char1,
       END OF ty_outtab_8007,

       BEGIN OF ty_outtab_7001,
         role  TYPE agr_name,
         begda TYPE begda,
         endda TYPE endda,
       END OF ty_outtab_7001,

       BEGIN OF ty_outtab_7002,
         userid TYPE xubname,
         risk   TYPE zrisk,
         owner  TYPE xubname,
       END OF ty_outtab_7002,

       BEGIN OF ty_outtab_7003,
         role   TYPE agr_name,
         reason TYPE text100,
       END OF ty_outtab_7003,

       BEGIN OF ty_outtab_7006,
         session_id TYPE zacg_session_id,
         ffid       TYPE xubname,
         owner      TYPE xubname,
         userid     TYPE xubname,
         tcode      TYPE tcode,
         times      TYPE i,
         reason     TYPE char100,
       END OF ty_outtab_7006,

       BEGIN OF ty_8007,
         request  TYPE zacg_acc_req,
         user     TYPE xubname,
         risk     TYPE zrisk,
         owner    TYPE xubname,
         role     TYPE agr_name,
         approver TYPE xubname,
       END OF ty_8007,

       BEGIN OF ty_file_error_9030,
         index TYPE sy-tabix,
         error TYPE text200,
       END OF ty_file_error_9030,

       BEGIN OF ty_outtab_9033,
         ffid     TYPE xubname,
         ffnm     TYPE ad_namtext,
         stat     TYPE icon_d,
         loid     TYPE xubname,
         lonm     TYPE ad_namtext,
         logn(60) TYPE c,
         logedin  TYPE flag,
         ucomm    TYPE syucomm,
         index    TYPE sy-tabix,
       END OF ty_outtab_9033,

       BEGIN OF ty_outtab_9034,
         ffid       TYPE xubname,
         owner      TYPE xubname,
         userid     TYPE xubname,
         session_id TYPE zacg_session_id,
         logindt    TYPE datum,
         logintm    TYPE uzeit,
         lgoutdt    TYPE datum,
         lgouttm    TYPE uzeit,
         tcode      TYPE tcode,
         times      TYPE i,
         box        TYPE flag,
       END OF ty_outtab_9034,

       BEGIN OF ty_outtab_9035,
         session   TYPE zacg_session_id,
         userid    TYPE xubname,
         clnt_ip   TYPE ssi_logon_client_ip,
         ffid      TYPE xubname,
         assessor  TYPE xubname,
         reason    TYPE zacg_ffid_rsn,
         frsn      TYPE icon_d,
         logindt   TYPE datum,
         logintm   TYPE uzeit,
         lgoutdt   TYPE datum,
         lgouttm   TYPE uzeit,
         assessed  TYPE char22,
         assmntdtl TYPE icon_d,
       END OF ty_outtab_9035,

       BEGIN OF ty_outtab_9036,
         slguser  TYPE xubname,
         sal_date TYPE datum,
         tcode    TYPE tcode,
         times    TYPE i,
         box      TYPE flag,
       END OF ty_outtab_9036,

       BEGIN OF ty_outtab_9037,
         req_no       TYPE zacg_acc_req,
         user         TYPE xubname,
         seqnr        TYPE seqnr,
         role         TYPE agr_name,
         begda        TYPE begda,
         endda        TYPE endda,
         approver     TYPE xubname,
         app_role     TYPE xubname,
         status       TYPE char50,
         statust      TYPE string,
         action_taken TYPE xfeld,
         ernam        TYPE ernam,
         erdat        TYPE erdat,
         reqact       TYPE char5,
         org_req_no   TYPE zacg_acc_req,
         aetim        TYPE uzeit,
         rj_rsn	      TYPE text100,
         box          TYPE c,
       END OF ty_outtab_9037,

       BEGIN OF ty_outtab_9042,
         head       TYPE char25,
         gb_advance TYPE p DECIMALS 1,
         gc_core    TYPE p DECIMALS 1,
         gd_self    TYPE p DECIMALS 1,
         not_class  TYPE p DECIMALS 1,
         tot_class  TYPE i,
         total      TYPE i,
       END OF ty_outtab_9042,

       BEGIN OF ty_outtab_8008,
         priority     TYPE zacg_rule_prio,
         rule_desc    TYPE zacg_rule_desc,
         agr_name	    TYPE agr_name,
         no_of_object TYPE int8,
       END OF ty_outtab_8008,

       BEGIN OF ty_outtab_6001,
         priority  TYPE zacg_rule_prio,
         rule_desc TYPE zacg_rule_desc,
         agr_name	 TYPE agr_name,
         object    TYPE agobject,
         value     TYPE agval,
       END OF ty_outtab_6001,

       BEGIN OF ty_file_data_9030,
         user    TYPE xubname,
         role    TYPE agr_name,
         start   TYPE string,
         end     TYPE string,
         manager TYPE string,
         owner   TYPE xubname,
       END OF ty_file_data_9030,

       BEGIN OF ty_file_data_9041_u,
         user TYPE xubname,
         role TYPE agr_name,
       END OF ty_file_data_9041_u,

       BEGIN OF ty_file_data_9041_r,
         agr_name TYPE agr_name,
         object	  TYPE agobject,
         field    TYPE agrfield,
         value    TYPE agval,
       END OF ty_file_data_9041_r,

       BEGIN OF ty_file_data_9042,
         agr_name TYPE agr_name,
         object   TYPE agobject,
         field    TYPE agrfield,
         value    TYPE agval,
       END OF ty_file_data_9042,

       BEGIN OF ty_file_data_9042_txt,
         dummy    TYPE string,
         agr_name TYPE agr_name,
         object   TYPE agobject,
         field    TYPE agrfield,
         value    TYPE agval,
       END OF ty_file_data_9042_txt,

       BEGIN OF ty_file_data_90411_txt,
         dummy    TYPE string,
         user     TYPE xubname,
         agr_name TYPE agr_name,
       END OF ty_file_data_90411_txt,

       BEGIN OF ty_file_data_90412_txt,
         dummy    TYPE string,
         agr_name TYPE agr_name,
         object   TYPE agobject,
         field    TYPE agrfield,
         value    TYPE agval,
       END OF ty_file_data_90412_txt,

       BEGIN OF ty_outtab_9041,
         head       TYPE char25,
         gb_advance TYPE p DECIMALS 1,
         gc_core    TYPE p DECIMALS 1,
         gd_self    TYPE p DECIMALS 1,
         not_class  TYPE p DECIMALS 1,
         tot_class  TYPE i,
         total      TYPE i,
       END OF ty_outtab_9041,

       BEGIN OF ty_outtab_8009,
         priority     TYPE zacg_rule_prio,
         rule_desc    TYPE zacg_rule_desc,
         user         TYPE xubname,
         no_of_object TYPE int8,
       END OF ty_outtab_8009,

       BEGIN OF ty_outtab_6002,
         priority     TYPE zacg_rule_prio,
         rule_desc    TYPE zacg_rule_desc,
         user         TYPE xubname,
         agr_name	    TYPE agr_name,
         no_of_object TYPE int8,
       END OF ty_outtab_6002,

       BEGIN OF ty_upload_file,
         field1 TYPE string,
         field2 TYPE string,
         field3 TYPE string,
         field4 TYPE string,
         field5 TYPE string,
         field6 TYPE string,
         field7 TYPE string,
       END OF ty_upload_file,

       BEGIN OF ty_outtab_5001,
         priority  TYPE zacg_rule_prio,
         rule_desc TYPE zacg_rule_desc,
         agr_name	 TYPE agr_name,
         object    TYPE agobject,
         value     TYPE agval,
       END OF ty_outtab_5001.

DATA:
  g_ucomm                TYPE sy-ucomm,
  g_title                TYPE string,
  g_subscr_nr            TYPE sy-dynnr VALUE '9000',
  g_subscr_nn            TYPE sy-dynnr,
  g_srole                TYPE agr_1251-agr_name,
  g_crole                TYPE agr_agrs-agr_name,
  g_user                 TYPE agr_users-uname,
  g_fusr                 TYPE zacg_ffid_hdr-ffid,
  g_module               TYPE zrisk_proc,
  g_upw                  TYPE bapibname-bapibname,
  g_role                 TYPE agr_name,
  g_rreq                 TYPE zacg_acc_req,
  g_file                 TYPE flag,
  g_8007_first           TYPE flag,
  g_9009_first           TYPE flag,
  g_9024_first           TYPE flag,
  g_9025_first           TYPE flag,
  g_9026_first           TYPE flag,
  g_9027_first           TYPE flag,
  g_9028_first           TYPE flag,
  g_9029_first           TYPE flag,
  g_9030_first           TYPE flag,
  g_9031_first           TYPE flag,
  g_9034_first           TYPE flag,
  g_9035_first           TYPE flag,
  g_9036_first           TYPE flag,
  g_9037_first           TYPE flag,
  g_9041_first           TYPE flag,
  g_9042_first           TYPE flag,
  g_agr_name             TYPE agr_name,
  g_stxbmaps             TYPE stxbitmaps,
  g_logo_url(255)        TYPE c,
  g_bytecnt              TYPE i,
  g_logo_size            TYPE i,
  g_mitigated            TYPE flag,
  g_request_number       TYPE zacg_acc_req,
  gv_rejection_reason    TYPE text100,
  g_refresh_9033(60)     TYPE c,
  g_tcode                TYPE tstc-tcode,
  cmonth                 TYPE c,
  lmonth                 TYPE c,
  lweek                  TYPE c,
  cweek                  TYPE c,
  yesterday              TYPE c,
  today                  TYPE c,
  custom                 TYPE c,
  date1                  TYPE datum,
  date2                  TYPE datum,
  hrs                    TYPE i,
  rg_1y                  TYPE c,
  rg_6m                  TYPE c,
  rg_lm                  TYPE c,
  rg_cm                  TYPE c,
  rg_cd                  TYPE c,

  wa_layout              TYPE lvc_s_layo,
  wa_outtab_7001         TYPE ty_outtab_7001,
  wa_outtab_7002         TYPE ty_outtab_7002,
  wa_outtab_7003         TYPE ty_outtab_7003,
  wa_outtab_9033         TYPE ty_outtab_9033,
  wa_selected_line_9033  TYPE ty_outtab_9033,
  wa_outtab_9034         TYPE ty_outtab_9034,
  wa_outtab_7006         TYPE ty_outtab_7006,


  gt_content             TYPE STANDARD TABLE OF bapiconten INITIAL SIZE 0,
  gt_logo_table          TYPE STANDARD TABLE OF ty_logo_table,
  gt_user_output         TYPE STANDARD TABLE OF ty_usr_output,
  gt_pwd_output          TYPE STANDARD TABLE OF ty_pwd_output,
  gt_lock_output         TYPE STANDARD TABLE OF ty_lock_output,
  gt_ffid_tlog           TYPE TABLE OF zacg_ffid_tlog,
  gt_role_des            TYPE TABLE OF ty_role_des,
  gt_dr_role             TYPE TABLE OF ty_dr_role,
  gt_comp_role           TYPE TABLE OF ty_comp_role,
  gt_del_role            TYPE TABLE OF ty_del_role,
  gt_pmast_role          TYPE TABLE OF ty_del_role,
  gt_ccomp_role          TYPE TABLE OF ty_ccomp_role,
  gt_user_details        TYPE TABLE OF ty_user_details,
  gt_role_output         TYPE TABLE OF ty_role_output,
  gt_copy_role           TYPE TABLE OF ty_copy_role,
  gt_auth_val            TYPE TABLE OF ty_auth_val,
  gt_derive_role         TYPE TABLE OF ty_derive_role,
  gt_org_field           TYPE TABLE OF ty_org_field,
  gt_outtab_9027         TYPE TABLE OF ty_outtab_9027,
  gt_outtab_9028         TYPE TABLE OF ty_outtab_9028,
  gt_outtab_9029         TYPE TABLE OF ty_outtab_9029,
  gt_file_error_9030     TYPE TABLE OF ty_file_error_9030,
  gt_outtab_9031         TYPE TABLE OF ty_outtab_9031,

  gt_bdctab              TYPE TABLE OF bdcdata,
  gt_message             TYPE TABLE OF bdcmsgcoll,
  gr_table               TYPE REF TO cl_salv_table,
  gt_lock_data           TYPE STANDARD TABLE OF sim_rsusr200_alv,
  gt_users               TYPE STANDARD TABLE OF ty_users,

  i_summary_9001         TYPE zacg_t_risk_summary,
  i_detail_9001          TYPE zacg_t_risk_detail,
  i_summary_9002         TYPE zacg_t_risk_summary,
  i_detail_9002          TYPE zacg_t_risk_detail,
  i_outtab_9009          TYPE STANDARD TABLE OF ty_outtab_9009,
  i_summary_9031         TYPE zacg_t_risk_summary,
  i_outtab_8007          TYPE STANDARD TABLE OF ty_outtab_8007,
  i_outtab_8007_sel_line TYPE STANDARD TABLE OF ty_8007,
  i_outtab_7002          TYPE STANDARD TABLE OF ty_outtab_7002,
  i_outtab_7001          TYPE STANDARD TABLE OF ty_outtab_7001,
  i_outtab_7003          TYPE STANDARD TABLE OF ty_outtab_7003,
  i_outtab_7006          TYPE STANDARD TABLE OF ty_outtab_7006,
  i_outtab_9030          TYPE STANDARD TABLE OF ty_file_error_9030,
  i_outtab_9033          TYPE STANDARD TABLE OF ty_outtab_9033,
  i_outtab_9034          TYPE STANDARD TABLE OF ty_outtab_9034,
  i_outtab_9035          TYPE STANDARD TABLE OF ty_outtab_9035,
  i_outtab_9036          TYPE STANDARD TABLE OF ty_outtab_9036,
  i_outtab_9037          TYPE STANDARD TABLE OF ty_outtab_9037,
  i_outtab_9042          TYPE STANDARD TABLE OF ty_outtab_9042,
  i_outtab_9042_s2       TYPE STANDARD TABLE OF ty_outtab_8008,
  i_outtab_9042_s3       TYPE STANDARD TABLE OF ty_outtab_6001,
  i_outtab_9041_s1       TYPE STANDARD TABLE OF ty_outtab_9041,
  i_outtab_9041_s2       TYPE STANDARD TABLE OF ty_outtab_8009,
  i_outtab_9041_s3       TYPE STANDARD TABLE OF ty_outtab_6002,
  i_outtab_9041_s4       TYPE STANDARD TABLE OF ty_outtab_5001,
  i_outtab_8008          TYPE STANDARD TABLE OF ty_outtab_8008,
  i_outtab_6001          TYPE STANDARD TABLE OF ty_outtab_6001,
  i_outtab_6002          TYPE STANDARD TABLE OF ty_outtab_6002,
  i_file_data_9030       TYPE STANDARD TABLE OF ty_file_data_9030,
  i_file_data_9041_u     TYPE STANDARD TABLE OF ty_file_data_9041_u,
  i_file_data_9041_r     TYPE STANDARD TABLE OF ty_file_data_9041_r,
  i_outtab_9041          TYPE STANDARD TABLE OF ty_outtab_9042,
  i_file_data_9042       TYPE STANDARD TABLE OF ty_file_data_9042,
  i_outtab_8009          TYPE STANDARD TABLE OF ty_outtab_8009,
  i_upload_file          TYPE STANDARD TABLE OF ty_upload_file,


  o_conttainer_9000      TYPE REF TO cl_gui_custom_container,
  o_picture_control      TYPE REF TO cl_gui_picture,
  o_conttainer_9007      TYPE REF TO cl_gui_custom_container,
  o_gui_alv_grid_9007    TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9008      TYPE REF TO cl_gui_custom_container,
  o_gui_alv_grid_9008    TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9006      TYPE REF TO cl_gui_custom_container,
  o_gui_alv_grid_9006    TYPE REF TO cl_gui_alv_grid,
  o_acg                  TYPE REF TO lcl_acg,
  o_conttainer_8001      TYPE REF TO cl_gui_custom_container,
  o_grid_8001            TYPE REF TO cl_gui_alv_grid,
  o_splitter_8001        TYPE REF TO cl_gui_splitter_container,
  o_top_cont_8001        TYPE REF TO cl_gui_container,
  o_bot_cont_8001        TYPE REF TO cl_gui_container,
  o_docu_8001            TYPE REF TO cl_dd_document,
  o_html_8001            TYPE REF TO cl_gui_html_viewer,
  o_conttainer_8002      TYPE REF TO cl_gui_custom_container,
  o_grid_8002            TYPE REF TO cl_gui_alv_grid,
  o_splitter_8002        TYPE REF TO cl_gui_splitter_container,
  o_top_cont_8002        TYPE REF TO cl_gui_container,
  o_bot_cont_8002        TYPE REF TO cl_gui_container,
  o_docu_8002            TYPE REF TO cl_dd_document,
  o_html_8002            TYPE REF TO cl_gui_html_viewer,
  o_conttainer_8003      TYPE REF TO cl_gui_custom_container,
  o_grid_8003            TYPE REF TO cl_gui_alv_grid,
  o_splitter_8003        TYPE REF TO cl_gui_splitter_container,
  o_top_cont_8003        TYPE REF TO cl_gui_container,
  o_bot_cont_8003        TYPE REF TO cl_gui_container,
  o_docu_8003            TYPE REF TO cl_dd_document,
  o_html_8003            TYPE REF TO cl_gui_html_viewer,
  o_conttainer_8004      TYPE REF TO cl_gui_custom_container,
  o_grid_8004            TYPE REF TO cl_gui_alv_grid,
  o_splitter_8004        TYPE REF TO cl_gui_splitter_container,
  o_top_cont_8004        TYPE REF TO cl_gui_container,
  o_bot_cont_8004        TYPE REF TO cl_gui_container,
  o_docu_8004            TYPE REF TO cl_dd_document,
  o_html_8004            TYPE REF TO cl_gui_html_viewer,
  o_conttainer_8005      TYPE REF TO cl_gui_custom_container,
  o_grid_8005            TYPE REF TO cl_gui_alv_grid,
  o_splitter_8005        TYPE REF TO cl_gui_splitter_container,
  o_top_cont_8005        TYPE REF TO cl_gui_container,
  o_bot_cont_8005        TYPE REF TO cl_gui_container,
  o_docu_8005            TYPE REF TO cl_dd_document,
  o_html_8005            TYPE REF TO cl_gui_html_viewer,
  o_conttainer_8006      TYPE REF TO cl_gui_custom_container,
  o_grid_8006            TYPE REF TO cl_gui_alv_grid,
  o_splitter_8006        TYPE REF TO cl_gui_splitter_container,
  o_top_cont_8006        TYPE REF TO cl_gui_container,
  o_bot_cont_8006        TYPE REF TO cl_gui_container,
  o_docu_8006            TYPE REF TO cl_dd_document,
  o_html_8006            TYPE REF TO cl_gui_html_viewer,
  o_conttainer_8007      TYPE REF TO cl_gui_custom_container,
  o_grid_8007            TYPE REF TO cl_gui_alv_grid,
  o_docu_8007            TYPE REF TO cl_dd_document,
  o_conttainer_9009      TYPE REF TO cl_gui_custom_container,
  o_grid_9009            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9010      TYPE REF TO cl_gui_custom_container,
  o_grid_9010            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9011      TYPE REF TO cl_gui_custom_container,
  o_grid_9011            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9012      TYPE REF TO cl_gui_custom_container,
  o_grid_9012            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9013      TYPE REF TO cl_gui_custom_container,
  o_grid_9013            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9014      TYPE REF TO cl_gui_custom_container,
  o_grid_9014            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9015      TYPE REF TO cl_gui_custom_container,
  o_grid_9015            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9016      TYPE REF TO cl_gui_custom_container,
  o_grid_9016            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9017      TYPE REF TO cl_gui_custom_container,
  o_grid_9017            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9018      TYPE REF TO cl_gui_custom_container,
  o_grid_9018            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9019      TYPE REF TO cl_gui_custom_container,
  o_grid_9019            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9020      TYPE REF TO cl_gui_custom_container,
  o_grid_9020            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9021      TYPE REF TO cl_gui_custom_container,
  o_grid_9021            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9022      TYPE REF TO cl_gui_custom_container,
  o_grid_9022            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9023      TYPE REF TO cl_gui_custom_container,
  o_grid_9023            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9024      TYPE REF TO cl_gui_custom_container,
  o_grid_9024            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9025      TYPE REF TO cl_gui_custom_container,
  o_grid_9025            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9026      TYPE REF TO cl_gui_custom_container,
  o_grid_9026            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9027      TYPE REF TO cl_gui_custom_container,
  o_grid_9027            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9028      TYPE REF TO cl_gui_custom_container,
  o_grid_9028            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9029      TYPE REF TO cl_gui_custom_container,
  o_grid_9029            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9030      TYPE REF TO cl_gui_custom_container,
  o_grid_9030            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9031      TYPE REF TO cl_gui_custom_container,
  o_grid_9031            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_7005      TYPE REF TO cl_gui_custom_container,
  o_textedit_7005        TYPE REF TO cl_gui_textedit,
  o_conttainer_9034      TYPE REF TO cl_gui_custom_container,
  o_grid_9034            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9035      TYPE REF TO cl_gui_custom_container,
  o_grid_9035            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9036      TYPE REF TO cl_gui_custom_container,
  o_grid_9036            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9037      TYPE REF TO cl_gui_custom_container,
  o_grid_9037            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9042      TYPE REF TO cl_gui_custom_container,
  o_grid_9042            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_8008      TYPE REF TO cl_gui_custom_container,
  o_grid_8008            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_6001      TYPE REF TO cl_gui_custom_container,
  o_grid_6001            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_9041      TYPE REF TO cl_gui_custom_container,
  o_grid_9041            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_8009      TYPE REF TO cl_gui_custom_container,
  o_grid_8009            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_6002      TYPE REF TO cl_gui_custom_container,
  o_grid_6002            TYPE REF TO cl_gui_alv_grid,
  o_conttainer_5001      TYPE REF TO cl_gui_custom_container,
  o_grid_5001            TYPE REF TO cl_gui_alv_grid.

CONTROLS:
  table_7001 TYPE TABLEVIEW USING SCREEN '7001',
  table_7002 TYPE TABLEVIEW USING SCREEN '7002',
  table_7003 TYPE TABLEVIEW USING SCREEN '7003',
  table_7006 TYPE TABLEVIEW USING SCREEN '7006',
  table_9033 TYPE TABLEVIEW USING SCREEN '9033'.

FIELD-SYMBOLS :
             <fs_data> TYPE ANY TABLE.


CONSTANTS : co_file_9009          TYPE string    VALUE '/Set Productive Password.xls',
            co_trans_name_9009    TYPE cxsltdesc VALUE 'ZACG_SET_PRODUC_PASS_TEM',
            co_file_9010          TYPE string    VALUE '/Update User Details.xls',
            co_trans_name_9010    TYPE cxsltdesc VALUE 'ZACG_UPDATE_USR_DETAIL_TEM',
            co_file_9011          TYPE string    VALUE '/Change Description of Roles.xls',
            co_trans_name_9011    TYPE cxsltdesc VALUE 'ZACG_ROLES_DESC_CHANGE_TEM',
            co_file_9012          TYPE string    VALUE '/Derive Role Creation.xls',
            co_trans_name_9012    TYPE cxsltdesc VALUE 'ZACG_DERIVE_ROLE_CREATE_TEM',
            co_file_9013          TYPE string    VALUE '/Delete Inheritance.xls',
            co_trans_name_9013    TYPE cxsltdesc VALUE 'ZACG_DELETE_INHERITANCE_TEM',
            co_file_9014          TYPE string    VALUE '/Add Single Role to Composite Role.xls',
            co_trans_name_9014    TYPE cxsltdesc VALUE 'ZACG_ADD_SINGLE_TO_COMP_TEM',
            co_file_9015          TYPE string    VALUE '/Remove Single Role from Composite Role.xls',
            co_trans_name_9015    TYPE cxsltdesc VALUE 'ZACG_REM_SINGLE_FROM_COMP_TMP',
            co_file_9016          TYPE string    VALUE '/Delete Roles.xls',
            co_trans_name_9016    TYPE cxsltdesc VALUE 'ZACG_DELETE_ROLES_TEM',
            co_file_9017          TYPE string    VALUE '/Push Master Role.xls',
            co_trans_name_9017    TYPE cxsltdesc VALUE 'ZACG_MASTER_ROLE_PUSH_TEM',
            co_file_9018          TYPE string    VALUE '/Create Composite Role.xls',
            co_trans_name_9018    TYPE cxsltdesc VALUE 'ZACG_CREATE_COMP_ROLE_TEM',
            co_file_9019          TYPE string    VALUE '/Create Single Role by Copying.xls',
            co_trans_name_9019    TYPE cxsltdesc VALUE 'ZACG_CREATE_SINGLE_ROLE_TEM',
            co_file_9020          TYPE string    VALUE '/Role Template.xls',
            co_trans_name_9020    TYPE cxsltdesc VALUE 'ZACG_ROLE_ASSIGNMENT_TEM',
            co_file_9024_add      TYPE string    VALUE '/Maintain Auth Values Add - In All Existing Objects.xls',
            co_file_9024_adi      TYPE string    VALUE '/Maintain Auth Values Add - In Specific Instance(s).xls',
            co_file_9024_del      TYPE string    VALUE '/Maintain Auth Values Del - From All Instance(s).xls',
            co_file_9024_dli      TYPE string    VALUE '/Maintain Auth Values Del - In Specific Instance(s).xls',
            co_file_9024_ins      TYPE string    VALUE '/Maintain Auth Values Add - In New Object.xls',
            co_file_9024_din      TYPE string    VALUE '/Deactivate - In Specific Instnce(s).xls',
            co_file_9024_ain      TYPE string    VALUE '/Activate - In Specific Instnce(s).xls',
            co_file_9024_ani      TYPE string    VALUE '/Maintain Auth Values Add - In New Instnce(s).xls',
            co_file_9024_atc      TYPE string    VALUE '/Add TCode to Role.xls',
            co_file_9024_dtc      TYPE string    VALUE '/Delete TCode from Role.xls',
            co_file_9024_csr      TYPE string    VALUE '/Add Single Role (BLANK).xls',
            co_trans_name_9024    TYPE cxsltdesc VALUE 'ZACG_MASS_MAINT_AUTH_TEM',
            co_trans_inst_9024    TYPE cxsltdesc VALUE 'ZACG_MASS_MAINT_AUTH_TEM_INST',
            co_trans_dinst_9024   TYPE cxsltdesc VALUE 'ZACG_MASS_MAINT_AUTH_DEACT_INS',
            co_trans_asninst_9024 TYPE cxsltdesc VALUE 'ZACG_MASS_MAINT_ADD_NEW_INS',
            co_trans_tcdagr_9024  TYPE cxsltdesc VALUE 'ZACG_MASS_MAINT_ADD_TCO_AGR',
            co_trans_dtcdagr_9024 TYPE cxsltdesc VALUE 'ZACG_MASS_MAINT_DEL_TCO_AGR',
            co_trans_csr_9024     TYPE cxsltdesc VALUE 'ZACG_MASS_MAINT_ADD_SNG_AGR',
            co_file_9027          TYPE string    VALUE '/Copy Users from Reference Users.xls',
            co_trans_name_9027    TYPE cxsltdesc VALUE 'ZACG_XSLT_USER_COPY_TEMPLATE',
            co_file_9030          TYPE string    VALUE '/Bulk Access Request.xls',
            co_trans_name_9030    TYPE cxsltdesc VALUE 'ZACG_XSLT_NEW_ACCESS_TEMPLATE'.


DATA:     ok_code LIKE sy-ucomm.
