PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZACG_TREE_CONTRL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZACG_TREE_CONTRL-NODE_KEY .
    FIELD ZACG_TREE_CONTRL-RELATKEY .
    FIELD ZACG_TREE_CONTRL-RELATSHIP .
    FIELD ZACG_TREE_CONTRL-HIDDEN .
    FIELD ZACG_TREE_CONTRL-DISABLED .
    FIELD ZACG_TREE_CONTRL-ISFOLDER .
    FIELD ZACG_TREE_CONTRL-N_IMAGE .
    FIELD ZACG_TREE_CONTRL-EXP_IMAGE .
    FIELD ZACG_TREE_CONTRL-STYLE .
    FIELD ZACG_TREE_CONTRL-LAST_HITEM .
    FIELD ZACG_TREE_CONTRL-NO_BRANCH .
    FIELD ZACG_TREE_CONTRL-EXPANDER .
    FIELD ZACG_TREE_CONTRL-TEXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZACG_TREE_CONTRL-NODE_KEY .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
